Another attempt for fixing:   Caused by: java.lang.NoSuchMethodError:     javax.ws.rs.core.Response$Status$Family.familyOf(I)    Ljavax/ws/rs/core/Response$Status$Family;